blackjack4494/yt-dlc

- youtube_dlc/extractor/tiktok.py
The JSON formatting of the response changed, corrected.
#TESTING
Successfully downloaded and played a tiktok video. Fixes #12
> Fixed tiktok.py

- README.md
---
---
The link in README explaining why youtube-dlc exist is down. I replaced it by the latest archive.
> use webarchive to fix a dead link in README

- youtube_dlc/extractor/youtube.py
The JS player URL could not be found anymore, possibly because of a change on Youtubes side.
---
---
Today, many youtube videos could not be resolved anymore, because the JS player url changed its location:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--no-warnings', '--dump-json', '--id', '--', 'WXzFCS72QIA']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.10.25
[debug] Git HEAD: 6f8557ec4
[debug] Python version 3.8.5 …
```
> Fixed problem with JS player URL

- youtube_dlc/extractor/bandcamp.py
- youtube_dlc/extractor/extractors.py
---
This fixes Bandcamp album downloads. #31 
It also fixes a subtle bug where track downloads sometimes had album names, rather than track names, as titles. This is because Bandcamp sometimes returns different embedded json for the exact same request! The previous version used mostly regexps, whereas this one uses the json embedded in the page.
One thing I changed is that, if you download an album, track numbers are included in the filenames. This is much preferable default behavior. I wasn't sure how to do it without an ugly subclass, though.
> [bandcamp] restore album downloads

- youtube_dlc/extractor/bandcamp.py
- youtube_dlc/extractor/extractors.py
---
Sorry, I didn't realize I broke tests with that previous pull. This removes the hack I added that set Bandcamp album downloads to have numbered filenames by default.
> [bandcamp] fix failing test. remove subclass hack

- youtube_dlc/extractor/mtv.py
Fix a problem introduced in 320724f964f09a5e1f08edd246464db4f0d297f9 where is extracted the ID from the url with self._match_id but the problem is that ID is not always present in the url passed so the title should be extracted as proposed by the fix (and like is done in _real_extract (see line 337))
> [mtv] Fix a missing match_id

- youtube_dlc/extractor/newgrounds.py
---
Fixes #27 
Video urls are no longer directly in the page, and another fetch and parse has to be done to get them.
Also replaced video test case that has been deleted.
> [newgrounds] fix: video download

- youtube_dlc/extractor/youtube.py
> [youtube] fix: extract mix playlist ids from ytInitialData (#33)

- youtube_dlc/extractor/extractors.py
- youtube_dlc/extractor/zoom.py
- youtube_dlc/extractor/zoomus.py
---
Fixes #107 
Original pull request: https://github.com/unqueued/youtube-dl-prs/tree/pr/24751
I think the password field detection needs updating, however it downloads public videos.
> [zoom] new extractor

- youtube_dlc/extractor/vlive.py
---
Fixes vlive extractor for their revamped website. This should address #60 to some degree but is tested only with VODs and not with other video types such as live video. Thanks to @robindz in https://github.com/blackjack4494/yt-dlc/issues/60#issuecomment-719923648 for investigation into the fix.
The basic extractor now supports both video urls (eg `https://www.vlive.tv/video/1326`) and video post urls that point to the same video (eg `https://vlive.tv/post/1-18244258` which points to the same example video `1326`).
Adds support for new channel url format. The old format followed the example `https://channels.vlive.tv/FCD4B` while the new format follows the example `https://www.vlive.tv/channel/FCD4B`. The old format redirects to the new format. Additionally …
> [vlive] fix extractor for revamped website

- youtube_dlc/extractor/zoom.py
---
This comment: https://github.com/blackjack4494/yt-dlc/pull/108#issuecomment-724576704 mentioned special url's which do not work with the current extractor, this fixes his specific url.
> [zoom] Fix url parsing for url's containing /share/ and dots

- youtube_dlc/downloader/common.py
- youtube_dlc/downloader/youtube_live_chat.py
---
---
This Pull Request fix some corner case that are triggered when yt-dlc is used through bibanon/tubeup:
* TypeError in downloader/common.py due to the 'sleep_interval_subtitles' params missing
* KeyError in downloader/youtube_live_chat.py when 'liveChatReplayContinuationData' doesn't have the 'continuation' key
> Fix issue triggered by tubeup

- youtube_dlc/extractor/youtube.py
---
We already had a few copies of Polymer-style pagination handling logic for certain circumstances, but now we're forced into using it for all playlists since we can no longer disable Polymer. Refactor the logic to move it to the parent class for all entry lists (including e.g. search results, feeds, and list of playlists), and generify a bit to cover the child classes' use cases.
Fixes #148.
> RFC: youtube: Polymer UI and JSON endpoints for playlists

- README.md
- youtube_dlc/YoutubeDL.py
- youtube_dlc/__init__.py
- youtube_dlc/options.py
Please follow the guide below
---
---
Adds a new option `--break-on-existing` to stop the download when a video that is already in the archive is encountered. This is usefull while archive large channels, for example.
The original author is @gergesh. This was a pull request that existed before the takedown. You can confirm with the author if needed the code is Unlicense
> Stop download after encountering video in archive

- youtube_dlc/extractor/southpark.py
Allow downloading English South Park episodes from the southpark.de
---
---
Previously, youtube-dlc wouldn't accept links to English videos on southpark.de. This patch would fix that.
> [SouthparkDe] Support for English URLs

- youtube_dlc/postprocessor/embedthumbnail.py
- youtube_dlc/postprocessor/ffmpeg.py
---
---
When only `-c copy` is passed to ffmpeg without `-map 0`, only the first stream of each type is copied. So multiple audio/subs are lost. 
This PR fixes this. Closes #193 
My knowledge of ffmpeg is very limited, so I don't know if this can have any side effects. Someone who is more familiar with ffmpeg needs to review this before merging
> [ffmpeg] Ensure all streams are copied

- youtube_dlc/extractor/vlive.py
---
---
This fixes issue #222 .
I have debugged the issue and found that program attempts to download http\://www.vlive.tv/video/${playlist_id}, instead of http\://www.vlive.tv/video/${playlist_video_id}, where playlist_video_id denotes one of video_id within the playlist.
As http\://www.vlive.tv/video/${playlist_id} is not a valid url, program fails when attempting to download it.
The fix will check the type of an entry using 'videoType', and if the type is 'PLAYLIST', it parses webpage data to obtain all the video_ids in the playlist.
Using the …
> [Vlive] Fix playlist handling when downloading a channel

- youtube_dlc/postprocessor/embedthumbnail.py
> [ffmpeg] Fix for os.rename error when embedding thumbnail to video in a different drive on windows

- youtube_dlc/extractor/youtube.py
---
---
Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.
Fixes #201 
Sometimes YouTube adds "promoted" content among other unwanted stuff in the search results. This would change the index position of the actual video content we want (as well as any continuation token) in the data. The previous code had a hard-coded index position for this and would …
> [youtube] fix: ytsearch not returning results sometimes due to promoted content

- make_win.bat
If UPX is in the PATH, a corrupt Windows executable is produced. This prevents the offending DLL from being packed with UPX.
> make_win.bat: don't use UPX to pack vcruntime140.dll

- youtube_dlc/extractor/itv.py
Not my changes, but from @franhp that didn't get merged on yt-dl on time
It supports BTCC new pages' schema from 2019 an on (/articles/ instead of /races/)
---
---
Not my changes, but from @franhp that didn't get merged on yt-dl on time
It supports BTCC new pages' schema from 2019 an on (/articles/ instead of /races/)
> ITV BTCC new pages' URL update (articles instead of races)

- youtube_dlc/extractor/extractors.py
- youtube_dlc/extractor/tmz.py
---
- [ x ] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [ x ] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ x ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)
- [ x ] I am the original author of this code and I am willing to release it under …
> [TMZ] Fix TMZ.com extractor
