blackjack4494/yt-dlc

- youtube_dlc/version.py
Hopefully fixed the pypi error now.
> Release 24.10.2020

- .github/ISSUE_TEMPLATE/1_broken_site.md
- .github/ISSUE_TEMPLATE/2_site_support_request.md
- .github/ISSUE_TEMPLATE/3_site_feature_request.md
- .github/ISSUE_TEMPLATE/4_bug_report.md
- .github/ISSUE_TEMPLATE/5_feature_request.md
- youtube_dlc/extractor/tiktok.py
- youtube_dlc/extractor/youtube.py
- youtube_dlc/version.py
[tiktok]
download link + cookie fix
#14 @merval @blackjack4494 
closes #12 
[youtube]
updated age gate fix
https://github.com/blackjack4494/yt-dlc/commit/fb2c9277bc16bbfb22ccc61bc913d9259f3e6ba9 @blackjack4494 
closes #13
> Release 26.10.2020

- youtube_dlc/extractor/urplay.py
---
---
Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.
The urplay.se extractor is broken due to website changes. This is a fix.
> Update to reflect website changes.

- youtube_dlc/extractor/xtube.py
---
Fixes #17 
Also removed one test case that no longer exists on the site.
> [xtube] fix extractor (#17)

- youtube_dlc/extractor/extractors.py
- youtube_dlc/extractor/skyitalia.py
---
Add a new extractor for the broadcaster Sky italian websites (video.sky.it, tg24.sky.it, arte.sky.it etc...)
> [skyitalia] Add new extractor

- youtube_dlc/extractor/brightcove.py
---
---
In the event when there are no available sources due to DRM controlled sources, return a DRM error and don't proceed with trying.
#28 reports that an ExtractorError "No video formats found". Which is true, because the formats list is empty, however it's empty because they are all locked. This provides a more informative message to the end-user.
Tried the URL provided in #28 and confirmed a DRM message is returned.
> Added DRM logic to brightcove

- docs/supportedsites.md
- youtube_dlc/extractor/extractors.py
- youtube_dlc/extractor/nitter.py
---
---
Add an extractor for [nitter](https://github.com/zedeus/nitter), a "free and open source alternative Twitter front-end focused on privacy."
> [nitter] Add new extractor

- youtube_dlc/extractor/youtube.py
---
Fixes #49 
Extracts music metadata from ytInitialData, if it exists.
> [youtube] fix: extract artist metadata from ytInitialData (#49)

- youtube_dlc/extractor/netzkino.py
---
---
The Netzkino extractor was broken before, this change makes it works again.
Support for comments was removed, since the website doesn't have comments
anymore.
> [Netzkino] Only use video id to find metadata

- youtube_dlc/extractor/adobepass.py
---
---
This fix had been proposed on yt-dl for a lengthy period of time but was never merged. It has been thoroughly tested but a large section of the community. Fixes #22
> Added Comcast_SSO fix

- youtube_dlc/extractor/skyitalia.py
---
Added geoblock message as requested **https://github.com/blackjack4494/yt-dlc/pull/40#issuecomment-719900135**
> [skyitalia] added geoblock msg

- youtube_dlc/extractor/youtube.py
---
---
Discussion for the fix can be found in #56
This fixes occasional "Unable to extract video data" caused by a change of YouTube's player.
> [Youtube] Fixed problem with new youtube player

- youtube_dlc/postprocessor/ffmpeg.py
---
---
Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.
Closes #84
> Don't try to embed/convert json subtitles generated by youtube livechat

- youtube_dlc/extractor/youtube.py
> [youtube] fix: mix playlist title

- youtube_dlc/extractor/la7.py
checks the presence of the protocol in the url to prevent errors.
> [la7] fix missing protocol

- youtube_dlc/extractor/youtube.py
---
Fixes #116 
Detects a type of playlist from Youtube Music
> [youtube] fix: Youtube Music playlists

- youtube_dlc/extractor/mailru.py
A missing commit that was not merged
https://github.com/unqueued/youtube-dl-prs/commit/f3f5b3939eede223537193b710e845a6d3e7c051
> [mailru] removed escaped braces, use urljoin, added tests

- youtube_dlc/downloader/external.py
> Fix external downloader when there is no http_header

- youtube_dlc/extractor/youtube.py
---
---
Changes the regular expressions in YoutubePlaylistsIE to accommodate the new JSON endpoint, fixing a bug where downloading a user's entire set of playlists no longer works.
> Fix #93 YoutubePlaylistsIE

- youtube_dlc/extractor/extractors.py
- youtube_dlc/extractor/thisvid.py
---
---
This is a new extractor for thisvid[.]com, cherry-picked from my PR at ytdl-org/youtube-dl#26060. The "KVS player" is used by a lot of different websites, so in theory this could be extended to a generic downloader, but i could not find documentation on how to do that.
> implement ThisVid extractor

- youtube_dlc/extractor/viki.py
---
---
The viki extractor has a new-ish way to find the subtitles, but it appears that for at least some videos on viki the `streamSubtitles` attribute is not available. (See log pasted below.) This PR simply wraps that code in a `try/except` and falls back to the old method in the cases that fail with the new method.
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', '--list-formats', …
```
> fall-back to the old way to fetch subtitles, if needed

- youtube_dlc/version.py
> Release 2020.11.11 the second.

- youtube_dlc/YoutubeDL.py
---
---
Cleaner implementation of https://github.com/blackjack4494/yt-dlc/pull/178
> Check IDs in the archive before downloading webpage

- docs/supportedsites.md
- youtube_dlc/extractor/bitwave.py
- youtube_dlc/extractor/extractors.py
---
adds support for livestreams and replays on bitwave.tv
> [bitwave.tv] new extractor

- youtube_dlc/extractor/bitchute.py
- youtube_dlc/extractor/generic.py
---
---
See title. Closes #204
> Detect embedded bitchute videos

- youtube_dlc/extractor/ina.py
> [ina] support mobile links

- youtube_dlc/extractor/extractors.py
- youtube_dlc/extractor/generic.py
- youtube_dlc/extractor/rcs.py
---
New extractor for the various websites of the italian media company RCS (corriere, gazzetta, etc)
This time I checked geoblock, it seems that the content is freely viewable.
> [Rcs] Add new extractor

- youtube_dlc/extractor/instagram.py
---
---
This is taken from youtube-dl PR ytdl-org/youtube-dl#26981
https://github.com/unqueued/youtube-dl-prs/commit/f7960affb7f51cb5cb7671031028cb9b1499b50e
Original instagram.py is from https://github.com/nao20010128nao/ytdl-patched/blob/master/youtube_dl/extractor/instagram.py
> [instagram] Fix extractor

- youtube_dlc/extractor/extractors.py
- youtube_dlc/extractor/gedi.py
- youtube_dlc/extractor/generic.py
---
New extractor for the various websites of the italian media company Gedi (huffpo italy, repubblica, lastampa + local newpapers etc)
This time I checked geoblock, it seems that the content is freely viewable.
> [Gedi] Add new extractor
